# See MongoId configuration information for details about these settings: 
# http://mongoid.org/en/mongoid/docs/installation.html#configuration
database:
    production:
        clients:
            default:
                hosts:
                    - localhost:7210
                database: aresmush
                options:
                    user: ares
                    password: make_a_good_password
        options:
            # These options are critical for proper Ares operation.  
            # You may experiment with other options at your own discretion.
            raise_not_found_error: false

    test:
        clients:
            default:
                hosts:
                    - localhost:7210
                database: arestest
                options:
                    user: ares
                    password: make_a_good_password
        options:
            # These options are critical for proper Ares operation. 
            # You may experiment with other options at your own discretion.
            raise_not_found_error: false
